version: '2.4'

services:
  app:
    build: .
    container_name: chat
    environment:
      - ENV=local
      - PG_HOST=hostPg
      - PG_PORT=5432
      - PG_USER=alex
      - PG_DB=dbNamePg
      - PG_SSLMODE=disable
      - PG_PASSWORD=secret
      - HTTP_PORT=8080
      - HTTP_TIMEOUT=4s
      - HTTP_IDLE_TIMEOUT=10s
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy

    networks:
      chat:
        aliases:
          - app

  postgresql:
    image: postgres:16-alpine
    container_name: postgresql-chat
    environment:
      - POSTGRES_DB=dbNamePg
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U alex" ]
      interval: 2s
      timeout: 2s
      retries: 2
      start_period: 2s
    networks:
      chat:
        aliases:
          - hostPg

networks:
  chat:
    driver: bridge
