version: '3.8'

services:
  app:
    build: .
    container_name: chat
    environment:
      - CONFIG_PATH=/usr/local/src/local.yaml
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgresql
    networks:
      - chat

  postgresql:
    image: postgres:14-alpine
    container_name: chat-psql
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "10000:10000"
    networks:
      - chat

networks:
  chat:
    driver: bridge
