env: "local" #dev, prod


pg-db:
  host: "hostPg"
  pg_port: "5432"
  username: "alex"
  dbname: "dbNamePg"
  sslmode: "disable"
  password: "secret"

http:
  port: "8080"
  timeout: "4s"
  idle_timeout: "10s"
