env: "local" #dev, prod


pg-db:
  username: "alex"
  host: "localhost"
  pg_port: "10000"
  dbname: "chat"
  sslmode: "disable"
  password: "secret"

http:
  port: "8080"
  timeout: "4s"
  idle_timeout: "10s"
