// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavigationTab() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<template x-if=\"open\"><div class=\"relative flex items-start min-h-screen 2xl:px-0 lg:px-4 px-5 pt-0 pb-0 mx-auto mt-1 max-w-7xl  rounded-t-3xl\"><div @click=\"open=false\" class=\"fixed inset-0 z-50 w-screen h-screen bg-white bg-opacity-50 backdrop-blur-sm\"></div><aside :class=\"{ &#39;-translate-x-full -ml-20&#39; : !open, &#39;z-50 top-0 left-0 pl-4 ease-out duration-300&#39; : &#39;z-20 top-[55px]&#39; }\" class=\"fixed block w-56 h-screen max-h-screen pt-20 pb-5 pr-5 overflow-scroll bg-white lg:pt-8 lg:pb-16 z-50 top-0 left-0 pl-4 ease-out duration-300\"><div class=\"absolute inset-0 flex items-center justify-end w-full h-full\"><div class=\"fixed top-[10px] w-px h-full bg-neutral-200\"></div></div><h4 class=\"relative px-2 py-1 mb-2 text-sm font-semibold rounded-md\">Getting Started</h4><div class=\"relative grid grid-flow-row text-sm mb-7 auto-rows-max\"><a href=\"/pines/docs/introduction\" class=\"group flex w-full items-center rounded-md border px-2 py-1.5 hover:underline border-transparent\">Introduction</a> <a href=\"/pines/docs/how-to-use\" class=\"group flex w-full items-center rounded-md border px-2 py-1.5 bg-gray-100 border-gray-200/60\">How to Use</a> <a href=\"/pines/docs/alpine-plugin\" class=\"group flex w-full items-center rounded-md border px-2 py-1.5 hover:underline border-transparent\">Alpine Plugin</a> <a href=\"/pines/docs/contribution\" class=\"group flex w-full items-center rounded-md border px-2 py-1.5 hover:underline border-transparent\">Contribution</a></div></aside></div></template>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
