name: heroku

on:

  push:
   branches: [ "master" ]
  pull_request:
   branches: [ "master" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build and push Docker image
        run: |
          docker build -t registry.heroku.com/tc-chat/web -f Dockerfile.txt .
          docker push registry.heroku.com/tc-chat/web

      - name: Release Docker image on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web --app tc-chat
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Ensure Docker is installed
#        run: docker --version
#
#      - name: Install Docker Compose
#        run: sudo apt-get update && sudo apt-get install -y docker-compose
#
#      - name: Run make build
#        run: make build
#
#      - name: Run make up
#        run: make up