name: heroku

on:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run make build
        run: make build

      - name: Run make up
        run: make up

      - name: Build, Push and Deploy to Heroku
        uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "tc-chat"
          heroku_email: "a.zayets1986@gmail.com"
          usedocker: true

